"""FastAPI endpoint for the Prescription Writer Agent."""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fastapi import FastAPI
from pydantic import BaseModel
from typing import Optional

from prescription_writer import generate_prescription_draft

app = FastAPI(title="Clinical Vision Copilot — Prescription Writer Agent API")


class DiagnosisInput(BaseModel):
    diagnosis: str
    age: Optional[int] = None
    sex: Optional[str] = None
    allergies: Optional[str] = None
    current_medications: Optional[str] = None


@app.get("/health")
def health():
    return {"status": "ok"}


@app.post("/prescribe")
def prescribe(payload: DiagnosisInput):
    result = generate_prescription_draft(
        diagnosis=payload.diagnosis, age=payload.age, sex=payload.sex,
        allergies=payload.allergies, current_medications=payload.current_medications,
    )
    result["disclaimer"] = (
        "THIS IS A DRAFT ONLY, generated by AI for physician review. It is "
        "NOT a valid prescription until reviewed, edited as needed, and "
        "signed by a licensed physician. Do not use this output directly "
        "with patients."
    )
    return result
